version: "3"
services:
  redis:
    image: "redis:7.0.9-alpine"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./docker-cache/redis:/data
  mongo:
    image: "mongo:6.0.5"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./docker-cache/mongodb:/data/db