redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:leaderboard}
